backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'offers'
    label: 'Предложения'
    format: 'json'
    folder: 'assets/content/offers'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Заголовок', name: 'title', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'string' }
      - { label: 'Изображение', name: 'img', widget: 'file' }
      - { label: 'Цена', name: 'price', widget: 'string' }
  - name: 'categories'
    label: 'Категории блюд'
    format: 'json'
    folder: 'assets/content/categories'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Заголовок категории', name: 'title', widget: 'string' }
  - name: 'items'
    label: 'Блюда'
    format: 'json'
    folder: 'assets/content/items'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Название', name: 'title', widget: 'string' }
      - { label: 'Описание', name: 'description', widget: 'string' }
      - { label: 'Изображение', name: 'img', widget: 'file' }
      - label: "Категория"
        name: "category"
        widget: "relation"
        collection: "categories"
        searchFields: ["title"]
        valueField: "title"